# Generated using https://godot-build-options-generator.github.io

disable_3d = "yes"
optimize = "size"
disable_advanced_gui = "yes"
module_arkit_enabled = "no"
module_bmp_enabled = "no"
module_bullet_enabled = "no"
module_camera_enabled = "no"
module_enet_enabled = "no"
module_hdr_enabled = "no"
module_mobile_vr_enabled = "no"
module_ogg_enabled = "no"
module_opus_enabled = "no"
module_visual_script_enabled = "no"
module_webm_enabled = "no"
